### ISSUE TITLE
[BUG] Missing helper function in the SU Complaince by Collection report

### ISSUE THREAD

**Issue by Ar5had07** [SCCM-Zone/CM-SRS-Dashboards#1]
![image](https://user-images.githubusercontent.com/46709367/72336880-86677c00-36b9-11ea-872d-e3b82736a00e.png)

Under 'Next Service Window' it says 'Missing helper function'.

**Comment by Ioan-Popovici** [comment]
That is by design, please read the prerequisites section here:
https://github.com/SCCM-Zone/CM-SRS-Dashboards/blob/master/README.md#Prerequisites

I'll probably move the readme file in the src folder
