### ISSUE TITLE
Scan status by collection - Unable to read the data set DevicesScanStateInfo of next data row

### ISSUE THREAD

**Issue by jiaokeye** [SCCM-Zone/CM-SRS-Dashboards#18]
when i use scan status by collection report failed

the error is:
An error occurred while processing the report（rsProcessingAborted）
unable to read the data set DevicesScanStateInfo of next data row（rsErrorReadingNextDataRow）

**Comment by Ioan-Popovici** [comment]
Hi @jiaokeye,

Don't worry we'll figure out what's wrong.
Please follow these steps so I can see what's wrong:

# Debug Steps

* Start PowerShell as admin
* Run `Get-Service SQLServerReportingServices | Stop-Service -Confirm` (Stop the reporting service)
* Go to the `<ReportingServerInstallPath>\Microsoft SQL Server Reporting Services\SSRS\LogFiles` and move all the files to a backup folder.
* Run `Get-Service SQLServerReportingServices | Start-Service` (Start the reporting service)
* Run one of the reports that fail
* Copy the `ReportingServicesService_<DateAndSequenceNumber>.log` to another location and sanitize it
* Post the log here (attach, do not copy/paste) so I can review it.

**Comment by jiaokeye** [comment]
this is my failed report log file
[Microsoft.ReportingServices.Portal.WebHost_03_13_2020_10_46_39.log](https://github.com/SCCM-Zone/CM-SRS-Dashboards/files/4327645/Microsoft.ReportingServices.Portal.WebHost_03_13_2020_10_46_39.log)
[ReportServerService__03_13_2020_10_46_39.log](https://github.com/SCCM-Zone/CM-SRS-Dashboards/files/4327646/ReportServerService__03_13_2020_10_46_39.log)

**Comment by Ioan-Popovici** [comment]
I’m pretty sure it’s your os language, I’ll have a look this weekend.

**Comment by jiaokeye** [comment]
thanks for your help

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Ioan-Popovici** [comment]
Please run this query and send me the result via e-mail if you are not comfortable with showing your wsus server name here

```T-SQL
SELECT TOP 10
	LastScanPackageLocation
FROM v_UpdateScanStatus
```

**Comment by Ioan-Popovici** [comment]
Wasn't accounting for NULL `LastScanPackageLocation`. Please take the new version of the report for a spin and let me know if it's working for you.

[CM Dasboard Releases](https://SCCM.Zone/CM-SRS-Dashboards-RELEASES)
