### ISSUE TITLE
[BUG] Invalid column name on a few reports

### ISSUE THREAD

**Issue by bbrownchg** [SCCM-Zone/CM-SRS-Dashboards#29]
First, these look awesome! I've installed 5.0.2 but am unfortunately running in to an issue with a few reports. Specifically, attempting to execute the Operating System - Version Compliance by Collection and Operating System - Windows 11 Readiness by Collection reports generate the following error:

> An error has occurred during report processing. (rsProcessingAborted)
>  Query execution failed for dataset 'ComplianceInfo'. (rsErrorExecutingCommand)
>  Invalid column name 'co'. Invalid column name 'l'.

I installed the reports via the automatic PowerShell script. Is this a bug or could there be something else wrong? I'm running SQL Server and SSRS 2017 and my ConfigMgr database is at the 140 compatibility level.

**Comment by Ioan-Popovici** [comment]
Hi,

This is by design, you need to add `co`, and `I` to MEMCM user discovery.

![CleanShot 2021-10-19 at 16 25 41@2x](https://user-images.githubusercontent.com/17069425/137919019-0de21ded-7f8d-4ced-b739-2cda11419654.png)

Thanks
